# Generated by Django 4.2 on 2025-11-22 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_usermembership_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='color',
            field=models.CharField(default='#667eea', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='icon',
            field=models.CharField(default='🎁', max_length=10),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
