# Generated by Django 4.2 on 2025-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hour',
            field=models.CharField(max_length=5),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
    ]
