# Generated by Django 4.2 on 2025-11-22 10:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
        ('reservations', '0002_alter_reservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('machine', 'hour')},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
    ]
